---
title: Input file
author: Simone Romiti
output: html_document
bibliography: biblio.bib  
csl: 2d-materials.csl
link-citations: true
---

The following programs work using an input file:

``` bash
hmc-u1.cc
measure-u1.cc
metropolis-u1.cc
```

The input files are read using the `yaml-cpp` library from https://yaml.org/.
The parameters are organized in a hierarchical tree structure, with no dandling global parameter.


## Geometry of the lattice

The geometry of the lattice is specified in the `geometry` YAML node.

- If `ndims<4`, the extra spatial directions are flattened (e.g. `ndims=3` $\to$ `Z=1`).
- If the user specifies `L`, it is automatically set `L=X=Y=Z`.

## `hmc-u1.cc`

This program can be used to perform the HMC evolution of a gauge configuration which:
- was previously generated
- is "hot" (random elements in the group)
- is "cold" (identity operator in the group)

It can be used in 3 ways:
  - hmc evolution (`hmc:do_hmc:true in the input file)
  - hmc evolution with online measurements (`omeas` node in the input file)
  - online measurements without hmc evolution (`hmc:do_hmc:false but `omeas` node in the input file).

### References

