## Available algorithms

The gauge configurations can be generated with the following Markov Chain Monte Carlo algorithms (see Refs.@gattringer2009quantum, @Ashton:2022grj for the theoretical background):

- Metropolis
- Hybrid Monte Carlo
- Heatbath + Overrelaxation
- Nested Sampling

for the following gauge groups: $\mathrm{U}(1)$, $\mathrm{SU}(2)$, $\mathrm{SU}(3)$.

The measurements can be generated either online (during the MCMC) or offline (on previously generated configurations). 
At present the supported observables are:

- Plaquette standard and clover-improved energy
- Glueball correlators
- "pion" correlator
- Wilson loops and static potential among $\bar{q} q$ pairs
- Wilson gradient flow

# Continuing the runs

- Each run produces/updates a file named `nconf_counter.txt` in the directory where the gauge configurations are stored. This file contains a header line and the values below. An example:
  ```{.bash}
  heat i path_conf
  1 1140 ./confs/config_u1.4.4.1.16.b1.900000.1140
  ```

- In the input file (see documentation on how to use the library), for each algorithm it is possible to apply a "restart_condition". This parameter determines if we start from a new configuration or if we continue from the last one (determined from the file `nconf_counter.txt`).
