---
title: "How to use the library"
author: Simone Romiti
date: last-modified
---

With the installation,
the following source code are generate executables.

These are the main executables, and work by passing a `yaml` input file as an argument (see instructions later):

- `main-u1.cpp` : $\mathrm{U}(1)$ gauge theory
- `main-su2.cpp`: $\mathrm{SU}(2)$ gauge theory
- `main-su3.cpp`: $\mathrm{SU}(3)$ gauge theory

For the following please look at the files to understand what they do and how to pass the input parameters from the command line.

- `kramers.cc`
- `test.cc`
- `tryreduce.cc`
- `scaling.cc`


# How to run the main programs for `u1`, `su2` and `su3`

The `main-*.cpp` programs work as follows:

```{.bash}
<executable_name> -f <yaml_input_file>
```

The input file is parsed by the external library [`yaml-cpp`](https://yaml.org/). The set of parameters is divided into blocks (parsed as YAML nodes) organized in a hierarchical tree structure.
Each block corresponds to some set or characteristics of the simulation. 

The implementation of the input file parsing works according to the following paradigm: the library contains the definition of `struct`s for the blocks of parameters and of each algorithm.
A function that parses the input file takes care of checking the consistency of the input file and of initializing the attributes of the `struct`s.

## Structure of the input file

Please look at the following **pseudo input file**  in order to figure out how to write one that suits your application:

```{.bash}
{{< include pseudo_input_file.yaml >}}
```


