---
title: "Installing the library"
author: Simone Romiti
date: last-modified
---

# Dependencies

The library has the following dependencies: 

- [`xtensor`](https://github.com/xtensor-stack/xtensor) 
- [`Eigen3`](https://eigen.tuxfamily.org/index.php?title=Main_Page)
- [`yaml-cpp`](https://github.com/jbeder/yaml-cpp)
- [`Boost`](https://www.boost.org/)

# Installing on a Debian-based distribution

On Debian and derived distributions (Ubuntu, Linux Mint, etc.) the library can be installed as follows.

First, we install the dependencies:

```{.bash}
sudo apt-get install xtensor-dev
sudo apt-get install libeigen3-dev
sudo apt install libyaml-cpp-dev 
sudo apt-get install libboost-all-dev
```

And then install the library itself:

```{.bash}
bdir=/path/to/your/build/directory/ # custom empty directory

cmake \
    -B ${bdir} \
    -S /path/to/your/source/directory/

make -j$(nproc) install
```


# Installing on most HPC machines

The dependencies of the library are often available on most HPC machines with, e.g. with
```{.bash}
module load <name_of_library>
```
If that is not the case, the libraries have to be compiled from source. Please see the `doc/installation_scripts/` folder for template installation scripts.

Once the dependencies are installed, please proceed by creating a build directory and from there run the following scripts in a `bash` shell:

```{.bash}
source ./load_modules.sh # optional, only if not installing dependencies from source
./install.sh
```

A template of the above scripts can be found in the `doc/installation_scripts/` folder.
In the `test` folder there is an input file example `main.input` with some information in its header.


